/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 1
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_ATlesson = 2,
  anon_sym_ATimage = 3,
  anon_sym_ATimage_DASHalt = 4,
  anon_sym_ATword = 5,
  anon_sym_EQ = 6,
  sym_sentence_marker = 7,
  sym_fill_marker = 8,
  anon_sym_ATquestion = 9,
  anon_sym_ATlu = 10,
  anon_sym_ATen = 11,
  anon_sym_ATdistractor_DASHlu = 12,
  anon_sym_ATdistractor_DASHen = 13,
  sym_lesson_id = 14,
  sym_quoted_string = 15,
  sym_blank = 16,
  sym__text = 17,
  sym_source_file = 18,
  sym_lesson_declaration = 19,
  sym_image_declaration = 20,
  sym_image_alt_declaration = 21,
  sym_word_entry = 22,
  sym_question_line = 23,
  sym_lu_line = 24,
  sym_en_line = 25,
  sym_distractor_lu_line = 26,
  sym_distractor_en_line = 27,
  aux_sym__lu_content = 28,
  aux_sym__en_content = 29,
  aux_sym_source_file_repeat1 = 30,
  alias_sym_english = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_ATlesson] = "@lesson",
  [anon_sym_ATimage] = "@image",
  [anon_sym_ATimage_DASHalt] = "@image-alt",
  [anon_sym_ATword] = "@word",
  [anon_sym_EQ] = "=",
  [sym_sentence_marker] = "sentence_marker",
  [sym_fill_marker] = "fill_marker",
  [anon_sym_ATquestion] = "@question",
  [anon_sym_ATlu] = "@lu",
  [anon_sym_ATen] = "@en",
  [anon_sym_ATdistractor_DASHlu] = "@distractor-lu",
  [anon_sym_ATdistractor_DASHen] = "@distractor-en",
  [sym_lesson_id] = "lesson_id",
  [sym_quoted_string] = "quoted_string",
  [sym_blank] = "blank",
  [sym__text] = "luxembourgish",
  [sym_source_file] = "source_file",
  [sym_lesson_declaration] = "lesson_declaration",
  [sym_image_declaration] = "image_declaration",
  [sym_image_alt_declaration] = "image_alt_declaration",
  [sym_word_entry] = "word_entry",
  [sym_question_line] = "question_line",
  [sym_lu_line] = "lu_line",
  [sym_en_line] = "en_line",
  [sym_distractor_lu_line] = "distractor_lu_line",
  [sym_distractor_en_line] = "distractor_en_line",
  [aux_sym__lu_content] = "_lu_content",
  [aux_sym__en_content] = "_en_content",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [alias_sym_english] = "english",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_ATlesson] = anon_sym_ATlesson,
  [anon_sym_ATimage] = anon_sym_ATimage,
  [anon_sym_ATimage_DASHalt] = anon_sym_ATimage_DASHalt,
  [anon_sym_ATword] = anon_sym_ATword,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_sentence_marker] = sym_sentence_marker,
  [sym_fill_marker] = sym_fill_marker,
  [anon_sym_ATquestion] = anon_sym_ATquestion,
  [anon_sym_ATlu] = anon_sym_ATlu,
  [anon_sym_ATen] = anon_sym_ATen,
  [anon_sym_ATdistractor_DASHlu] = anon_sym_ATdistractor_DASHlu,
  [anon_sym_ATdistractor_DASHen] = anon_sym_ATdistractor_DASHen,
  [sym_lesson_id] = sym_lesson_id,
  [sym_quoted_string] = sym_quoted_string,
  [sym_blank] = sym_blank,
  [sym__text] = sym__text,
  [sym_source_file] = sym_source_file,
  [sym_lesson_declaration] = sym_lesson_declaration,
  [sym_image_declaration] = sym_image_declaration,
  [sym_image_alt_declaration] = sym_image_alt_declaration,
  [sym_word_entry] = sym_word_entry,
  [sym_question_line] = sym_question_line,
  [sym_lu_line] = sym_lu_line,
  [sym_en_line] = sym_en_line,
  [sym_distractor_lu_line] = sym_distractor_lu_line,
  [sym_distractor_en_line] = sym_distractor_en_line,
  [aux_sym__lu_content] = aux_sym__lu_content,
  [aux_sym__en_content] = aux_sym__en_content,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [alias_sym_english] = alias_sym_english,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATlesson] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATimage] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATimage_DASHalt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATword] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_sentence_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_fill_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATquestion] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATlu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATen] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATdistractor_DASHlu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATdistractor_DASHen] = {
    .visible = true,
    .named = false,
  },
  [sym_lesson_id] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_blank] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_lesson_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_image_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_image_alt_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_word_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_question_line] = {
    .visible = true,
    .named = true,
  },
  [sym_lu_line] = {
    .visible = true,
    .named = true,
  },
  [sym_en_line] = {
    .visible = true,
    .named = true,
  },
  [sym_distractor_lu_line] = {
    .visible = true,
    .named = true,
  },
  [sym_distractor_en_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__lu_content] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__en_content] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_english] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_english,
  },
  [2] = {
    [1] = alias_sym_english,
  },
  [3] = {
    [3] = alias_sym_english,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(56);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '=') ADVANCE(62);
      if (lookahead == '@') ADVANCE(10);
      if (lookahead == '[') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(48);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        'd', 20,
        'e', 27,
        'f', 21,
        'i', 26,
        'l', 15,
        'q', 50,
        's', 14,
        'w', 33,
      );
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(42);
      if (lookahead == 'u') ADVANCE(66);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(30);
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == 'g') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 26:
      if (lookahead == 'm') ADVANCE(5);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(67);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(2);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 49:
      if (lookahead == 'u') ADVANCE(68);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 53:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(4);
      END_STATE();
    case 54:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"') ADVANCE(1);
      END_STATE();
    case 55:
      if (eof) ADVANCE(56);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '@') ADVANCE(10);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(55);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '=' &&
          lookahead != ']') ADVANCE(74);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_ATlesson);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_ATimage);
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_ATimage_DASHalt);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_ATword);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_sentence_marker);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_fill_marker);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_ATquestion);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_ATlu);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_ATen);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_ATdistractor_DASHlu);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_ATdistractor_DASHen);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_lesson_id);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_blank);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != '=' &&
          lookahead != '@' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '=' &&
          lookahead != '@' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(74);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 55},
  [5] = {.lex_state = 55},
  [6] = {.lex_state = 55},
  [7] = {.lex_state = 55},
  [8] = {.lex_state = 55},
  [9] = {.lex_state = 55},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 55},
  [17] = {.lex_state = 55},
  [18] = {.lex_state = 55},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 55},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 55},
  [23] = {.lex_state = 55},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 55},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_ATlesson] = ACTIONS(1),
    [anon_sym_ATimage] = ACTIONS(1),
    [anon_sym_ATimage_DASHalt] = ACTIONS(1),
    [anon_sym_ATword] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_sentence_marker] = ACTIONS(1),
    [sym_fill_marker] = ACTIONS(1),
    [anon_sym_ATquestion] = ACTIONS(1),
    [anon_sym_ATlu] = ACTIONS(1),
    [anon_sym_ATen] = ACTIONS(1),
    [anon_sym_ATdistractor_DASHlu] = ACTIONS(1),
    [anon_sym_ATdistractor_DASHen] = ACTIONS(1),
    [sym_lesson_id] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_blank] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym_lesson_declaration] = STATE(2),
    [sym_image_declaration] = STATE(2),
    [sym_image_alt_declaration] = STATE(2),
    [sym_word_entry] = STATE(2),
    [sym_question_line] = STATE(2),
    [sym_lu_line] = STATE(2),
    [sym_en_line] = STATE(2),
    [sym_distractor_lu_line] = STATE(2),
    [sym_distractor_en_line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_ATlesson] = ACTIONS(7),
    [anon_sym_ATimage] = ACTIONS(9),
    [anon_sym_ATimage_DASHalt] = ACTIONS(11),
    [anon_sym_ATword] = ACTIONS(13),
    [sym_sentence_marker] = ACTIONS(5),
    [sym_fill_marker] = ACTIONS(5),
    [anon_sym_ATquestion] = ACTIONS(15),
    [anon_sym_ATlu] = ACTIONS(17),
    [anon_sym_ATen] = ACTIONS(19),
    [anon_sym_ATdistractor_DASHlu] = ACTIONS(21),
    [anon_sym_ATdistractor_DASHen] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym_lesson_declaration] = STATE(3),
    [sym_image_declaration] = STATE(3),
    [sym_image_alt_declaration] = STATE(3),
    [sym_word_entry] = STATE(3),
    [sym_question_line] = STATE(3),
    [sym_lu_line] = STATE(3),
    [sym_en_line] = STATE(3),
    [sym_distractor_lu_line] = STATE(3),
    [sym_distractor_en_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_comment] = ACTIONS(27),
    [anon_sym_ATlesson] = ACTIONS(7),
    [anon_sym_ATimage] = ACTIONS(9),
    [anon_sym_ATimage_DASHalt] = ACTIONS(11),
    [anon_sym_ATword] = ACTIONS(13),
    [sym_sentence_marker] = ACTIONS(27),
    [sym_fill_marker] = ACTIONS(27),
    [anon_sym_ATquestion] = ACTIONS(15),
    [anon_sym_ATlu] = ACTIONS(17),
    [anon_sym_ATen] = ACTIONS(19),
    [anon_sym_ATdistractor_DASHlu] = ACTIONS(21),
    [anon_sym_ATdistractor_DASHen] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_lesson_declaration] = STATE(3),
    [sym_image_declaration] = STATE(3),
    [sym_image_alt_declaration] = STATE(3),
    [sym_word_entry] = STATE(3),
    [sym_question_line] = STATE(3),
    [sym_lu_line] = STATE(3),
    [sym_en_line] = STATE(3),
    [sym_distractor_lu_line] = STATE(3),
    [sym_distractor_en_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_comment] = ACTIONS(31),
    [anon_sym_ATlesson] = ACTIONS(34),
    [anon_sym_ATimage] = ACTIONS(37),
    [anon_sym_ATimage_DASHalt] = ACTIONS(40),
    [anon_sym_ATword] = ACTIONS(43),
    [sym_sentence_marker] = ACTIONS(31),
    [sym_fill_marker] = ACTIONS(31),
    [anon_sym_ATquestion] = ACTIONS(46),
    [anon_sym_ATlu] = ACTIONS(49),
    [anon_sym_ATen] = ACTIONS(52),
    [anon_sym_ATdistractor_DASHlu] = ACTIONS(55),
    [anon_sym_ATdistractor_DASHen] = ACTIONS(58),
  },
  [STATE(4)] = {
    [aux_sym__lu_content] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_comment] = ACTIONS(63),
    [anon_sym_ATlesson] = ACTIONS(63),
    [anon_sym_ATimage] = ACTIONS(63),
    [anon_sym_ATimage_DASHalt] = ACTIONS(63),
    [anon_sym_ATword] = ACTIONS(63),
    [sym_sentence_marker] = ACTIONS(63),
    [sym_fill_marker] = ACTIONS(63),
    [anon_sym_ATquestion] = ACTIONS(63),
    [anon_sym_ATlu] = ACTIONS(63),
    [anon_sym_ATen] = ACTIONS(63),
    [anon_sym_ATdistractor_DASHlu] = ACTIONS(63),
    [anon_sym_ATdistractor_DASHen] = ACTIONS(63),
    [sym_blank] = ACTIONS(65),
    [sym__text] = ACTIONS(68),
  },
  [STATE(5)] = {
    [aux_sym__en_content] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(71),
    [sym_comment] = ACTIONS(73),
    [anon_sym_ATlesson] = ACTIONS(73),
    [anon_sym_ATimage] = ACTIONS(73),
    [anon_sym_ATimage_DASHalt] = ACTIONS(73),
    [anon_sym_ATword] = ACTIONS(73),
    [sym_sentence_marker] = ACTIONS(73),
    [sym_fill_marker] = ACTIONS(73),
    [anon_sym_ATquestion] = ACTIONS(73),
    [anon_sym_ATlu] = ACTIONS(73),
    [anon_sym_ATen] = ACTIONS(73),
    [anon_sym_ATdistractor_DASHlu] = ACTIONS(73),
    [anon_sym_ATdistractor_DASHen] = ACTIONS(73),
    [sym_blank] = ACTIONS(75),
    [sym__text] = ACTIONS(77),
  },
  [STATE(6)] = {
    [aux_sym__lu_content] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(79),
    [sym_comment] = ACTIONS(81),
    [anon_sym_ATlesson] = ACTIONS(81),
    [anon_sym_ATimage] = ACTIONS(81),
    [anon_sym_ATimage_DASHalt] = ACTIONS(81),
    [anon_sym_ATword] = ACTIONS(81),
    [sym_sentence_marker] = ACTIONS(81),
    [sym_fill_marker] = ACTIONS(81),
    [anon_sym_ATquestion] = ACTIONS(81),
    [anon_sym_ATlu] = ACTIONS(81),
    [anon_sym_ATen] = ACTIONS(81),
    [anon_sym_ATdistractor_DASHlu] = ACTIONS(81),
    [anon_sym_ATdistractor_DASHen] = ACTIONS(81),
    [sym_blank] = ACTIONS(83),
    [sym__text] = ACTIONS(85),
  },
  [STATE(7)] = {
    [aux_sym__lu_content] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(87),
    [sym_comment] = ACTIONS(89),
    [anon_sym_ATlesson] = ACTIONS(89),
    [anon_sym_ATimage] = ACTIONS(89),
    [anon_sym_ATimage_DASHalt] = ACTIONS(89),
    [anon_sym_ATword] = ACTIONS(89),
    [sym_sentence_marker] = ACTIONS(89),
    [sym_fill_marker] = ACTIONS(89),
    [anon_sym_ATquestion] = ACTIONS(89),
    [anon_sym_ATlu] = ACTIONS(89),
    [anon_sym_ATen] = ACTIONS(89),
    [anon_sym_ATdistractor_DASHlu] = ACTIONS(89),
    [anon_sym_ATdistractor_DASHen] = ACTIONS(89),
    [sym_blank] = ACTIONS(83),
    [sym__text] = ACTIONS(85),
  },
  [STATE(8)] = {
    [aux_sym__en_content] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(91),
    [sym_comment] = ACTIONS(93),
    [anon_sym_ATlesson] = ACTIONS(93),
    [anon_sym_ATimage] = ACTIONS(93),
    [anon_sym_ATimage_DASHalt] = ACTIONS(93),
    [anon_sym_ATword] = ACTIONS(93),
    [sym_sentence_marker] = ACTIONS(93),
    [sym_fill_marker] = ACTIONS(93),
    [anon_sym_ATquestion] = ACTIONS(93),
    [anon_sym_ATlu] = ACTIONS(93),
    [anon_sym_ATen] = ACTIONS(93),
    [anon_sym_ATdistractor_DASHlu] = ACTIONS(93),
    [anon_sym_ATdistractor_DASHen] = ACTIONS(93),
    [sym_blank] = ACTIONS(95),
    [sym__text] = ACTIONS(98),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym__text,
    ACTIONS(103), 13,
      sym_comment,
      anon_sym_ATlesson,
      anon_sym_ATimage,
      anon_sym_ATimage_DASHalt,
      anon_sym_ATword,
      sym_sentence_marker,
      sym_fill_marker,
      anon_sym_ATquestion,
      anon_sym_ATlu,
      anon_sym_ATen,
      anon_sym_ATdistractor_DASHlu,
      anon_sym_ATdistractor_DASHen,
      sym_blank,
  [20] = 2,
    ACTIONS(107), 1,
      anon_sym_ATimage,
    ACTIONS(105), 12,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_ATlesson,
      anon_sym_ATimage_DASHalt,
      anon_sym_ATword,
      sym_sentence_marker,
      sym_fill_marker,
      anon_sym_ATquestion,
      anon_sym_ATlu,
      anon_sym_ATen,
      anon_sym_ATdistractor_DASHlu,
      anon_sym_ATdistractor_DASHen,
  [38] = 2,
    ACTIONS(111), 1,
      anon_sym_ATimage,
    ACTIONS(109), 12,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_ATlesson,
      anon_sym_ATimage_DASHalt,
      anon_sym_ATword,
      sym_sentence_marker,
      sym_fill_marker,
      anon_sym_ATquestion,
      anon_sym_ATlu,
      anon_sym_ATen,
      anon_sym_ATdistractor_DASHlu,
      anon_sym_ATdistractor_DASHen,
  [56] = 2,
    ACTIONS(115), 1,
      anon_sym_ATimage,
    ACTIONS(113), 12,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_ATlesson,
      anon_sym_ATimage_DASHalt,
      anon_sym_ATword,
      sym_sentence_marker,
      sym_fill_marker,
      anon_sym_ATquestion,
      anon_sym_ATlu,
      anon_sym_ATen,
      anon_sym_ATdistractor_DASHlu,
      anon_sym_ATdistractor_DASHen,
  [74] = 2,
    ACTIONS(119), 1,
      anon_sym_ATimage,
    ACTIONS(117), 12,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_ATlesson,
      anon_sym_ATimage_DASHalt,
      anon_sym_ATword,
      sym_sentence_marker,
      sym_fill_marker,
      anon_sym_ATquestion,
      anon_sym_ATlu,
      anon_sym_ATen,
      anon_sym_ATdistractor_DASHlu,
      anon_sym_ATdistractor_DASHen,
  [92] = 2,
    ACTIONS(123), 1,
      anon_sym_ATimage,
    ACTIONS(121), 12,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_ATlesson,
      anon_sym_ATimage_DASHalt,
      anon_sym_ATword,
      sym_sentence_marker,
      sym_fill_marker,
      anon_sym_ATquestion,
      anon_sym_ATlu,
      anon_sym_ATen,
      anon_sym_ATdistractor_DASHlu,
      anon_sym_ATdistractor_DASHen,
  [110] = 2,
    ACTIONS(127), 1,
      anon_sym_ATimage,
    ACTIONS(125), 12,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_ATlesson,
      anon_sym_ATimage_DASHalt,
      anon_sym_ATword,
      sym_sentence_marker,
      sym_fill_marker,
      anon_sym_ATquestion,
      anon_sym_ATlu,
      anon_sym_ATen,
      anon_sym_ATdistractor_DASHlu,
      anon_sym_ATdistractor_DASHen,
  [128] = 3,
    ACTIONS(129), 1,
      sym_blank,
    ACTIONS(131), 1,
      sym__text,
    STATE(7), 1,
      aux_sym__lu_content,
  [138] = 3,
    ACTIONS(77), 1,
      sym__text,
    ACTIONS(133), 1,
      sym_blank,
    STATE(5), 1,
      aux_sym__en_content,
  [148] = 3,
    ACTIONS(135), 1,
      sym_blank,
    ACTIONS(137), 1,
      sym__text,
    STATE(6), 1,
      aux_sym__lu_content,
  [158] = 1,
    ACTIONS(139), 1,
      sym_lesson_id,
  [162] = 1,
    ACTIONS(141), 1,
      sym__text,
  [166] = 1,
    ACTIONS(143), 1,
      sym_quoted_string,
  [170] = 1,
    ACTIONS(145), 1,
      sym__text,
  [174] = 1,
    ACTIONS(147), 1,
      sym__text,
  [178] = 1,
    ACTIONS(149), 1,
      sym_quoted_string,
  [182] = 1,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
  [186] = 1,
    ACTIONS(153), 1,
      sym_quoted_string,
  [190] = 1,
    ACTIONS(155), 1,
      anon_sym_EQ,
  [194] = 1,
    ACTIONS(157), 1,
      sym__text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 20,
  [SMALL_STATE(11)] = 38,
  [SMALL_STATE(12)] = 56,
  [SMALL_STATE(13)] = 74,
  [SMALL_STATE(14)] = 92,
  [SMALL_STATE(15)] = 110,
  [SMALL_STATE(16)] = 128,
  [SMALL_STATE(17)] = 138,
  [SMALL_STATE(18)] = 148,
  [SMALL_STATE(19)] = 158,
  [SMALL_STATE(20)] = 162,
  [SMALL_STATE(21)] = 166,
  [SMALL_STATE(22)] = 170,
  [SMALL_STATE(23)] = 174,
  [SMALL_STATE(24)] = 178,
  [SMALL_STATE(25)] = 182,
  [SMALL_STATE(26)] = 186,
  [SMALL_STATE(27)] = 190,
  [SMALL_STATE(28)] = 194,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__lu_content, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__lu_content, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lu_content, 2, 0, 0), SHIFT_REPEAT(4),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lu_content, 2, 0, 0), SHIFT_REPEAT(4),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_en_line, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_en_line, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_question_line, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_question_line, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lu_line, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lu_line, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__en_content, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__en_content, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__en_content, 2, 0, 0), SHIFT_REPEAT(8),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__en_content, 2, 0, 0), SHIFT_REPEAT(9),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__en_content, 1, 0, 1),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__en_content, 1, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_alt_declaration, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image_alt_declaration, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_distractor_lu_line, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_distractor_lu_line, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_distractor_en_line, 2, 0, 2),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_distractor_en_line, 2, 0, 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lesson_declaration, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lesson_declaration, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_declaration, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image_declaration, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_entry, 4, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word_entry, 4, 0, 3),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [151] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_letz(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "letz",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
